config/routes.rb
Rails.application.routes.draw do
  resources :pizzas
  resources :toppings
  root 'pizzas#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def downcase_name
    self.name = name.downcase
  end
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :pizza_toppings, dependent: :destroy
  has_many :toppings, through: :pizza_toppings
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validate :unique_toppings_combination

  before_save :downcase_name

  def unique_toppings_combination
    matching_pizza = Pizza.includes(:toppings)
                          .where.not(id: id)
                          .select { |pizza| pizza.topping_ids.sort == topping_ids.sort }
                          .any?
    errors.add(:base, 'A pizza with this combination of toppings already exists.') if matching_pizza
  end

  def in_stock_toppings
    toppings.where(in_stock: true)
  end

  def out_of_stock_toppings
    toppings.where(in_stock: false)
  end
end

app/models/pizza_topping.rb
class PizzaTopping < ApplicationRecord
  belongs_to :pizza
  belongs_to :topping
end

app/models/topping.rb
class Topping < ApplicationRecord
  has_many :pizza_toppings
  has_many :pizzas, through: :pizza_toppings
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  
  before_save :downcase_name
  before_destroy :remove_from_pizzas

  scope :sorted_by_stock_and_name, -> {
    order(in_stock: :desc, name: :asc)
  }

  def self.create_or_update(topping_params)
    topping_name = topping_params[:name].downcase
    topping = find_by(name: topping_name)

    if topping
      if !topping.in_stock
        topping.update(in_stock: true)
        return topping, 'Topping is now back in stock.'
      else
        return topping, 'Topping already exists and is in stock.'
      end
    else
      topping = Topping.new(topping_params)
      if topping.save
        return topping, 'Topping was successfully created.'
      else
        return topping, 'Failed to create topping.'
      end
    end
  end

  private

  def remove_from_pizzas
    self.pizzas.each do |pizza|
      pizza.toppings.delete(self)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home
  end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]
  before_action :set_toppings, only: [:new, :create, :edit, :update]

  def index
    @pizzas = Pizza.all
  end

  def show
  end

  def new
    @pizza = Pizza.new
  end

  def create
    @pizza = Pizza.new(pizza_params)
    
    if @pizza.save
      flash[:notice] = 'Pizza was successfully created.'
      redirect_to @pizza
    else
      render :new
    end
  end

  def edit
    @pizza = Pizza.find(params[:id])
  end

  def update
    if @pizza.update(pizza_params)
      flash[:notice] = 'Pizza was successfully created.'
      redirect_to @pizza, notice: 'Pizza was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pizza.destroy
    redirect_to pizzas_url, notice: 'Pizza was successfully deleted.'
  end

  def home
    @pizzas = Pizza.all
  end

  private

  def set_pizza
    @pizza = Pizza.find(params[:id])
  end
  
  def set_toppings
    @toppings = Topping.all
  end

  def pizza_params
    params.require(:pizza).permit(:name, topping_ids: [])
  end
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  before_action :set_topping, only: [:show, :edit, :update, :destroy]

  def index
    @toppings = Topping.all
  end

  def show
  end

  def new
    @topping = Topping.new
  end

  def create
    @topping, notice = Topping.create_or_update(topping_params)
    redirect_to @topping, notice: notice
  end

  def edit
    @toppings = Topping.all
  end

  def update
    @topping = Topping.find(params[:id])
    if @topping.update(topping_params)
      redirect_to toppings_path
    else
      flash[:notice] = 'There was an error updating the topping: ' + @topping.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @topping = Topping.find(params[:id])
    @topping.destroy
    redirect_to toppings_path, notice: 'Topping was successfully deleted and removed from associated pizzas'
  end

  private

  def set_topping
    @topping = Topping.find(params[:id])
  end

  def topping_params
    params.require(:topping).permit(:name, :in_stock)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/views/application/home.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Welcome to The Pizza Store!</h1>

  <p>To update the menu, please use our Toppings and Pizza managers!</p>

  <ul class="nav nav-pills mb-4">
    <li class="nav-item">
      <%= link_to 'Toppings Manager', toppings_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Pizza Manager', pizzas_path, class: 'nav-link' %>
    </li>
  </ul>

  <h2 class="mb-3">Pizza Menu</h2>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Toppings</th>
      </tr>
    </thead>
    <tbody>
      <% @pizzas.each do |pizza| %>
        <tr>
          <td><%= pizza.name.capitalize %></td>
          <td><%= pizza.toppings.map { |topping| topping.name.capitalize }.join(', ') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pizzas/edit.html.erb
<div class="container mt-5">
  <h1>Edit Pizza</h1>

   <div class="mb-3">
    <%= link_to 'Menu', '/', class: 'btn btn-secondary' %>
    <%= link_to 'Toppings Manager', toppings_path, class: 'btn btn-primary' %>
  </div>

  <%= form_with(model: @pizza, url: pizza_path(@pizza), local: true) do |form| %>
    <% if @pizza.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h4><%= pluralize(@pizza.errors.count, 'error') %> prohibited this pizza from being saved:</h4>
        <ul>
          <% @pizza.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, 'Pizza Name' %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :topping_ids, 'Toppings' %>
      <% @toppings.sorted_by_stock_and_name.each do |topping| %>
        <div class="form-check">
          <%= form.check_box :topping_ids, { multiple: true, checked: @pizza.toppings.include?(topping) }, topping.id, nil %>
          <% if topping.in_stock %>
            <%= label_tag "pizza_topping_ids_#{topping.id}", topping.name, class: 'form-check-label' %>
          <% else %>
            <%= label_tag "pizza_topping_ids_#{topping.id}", "#{topping.name} (out of stock)", class: 'form-check-label text-danger' %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.submit "Update Pizza", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/pizzas/index.html.erb
<div class="container mt-5">
  <h2 class="mb-4">Pizza Manager</h2>

  <div class="mb-3">
    <%= link_to 'Menu', '/', class: 'btn btn-secondary' %>
    <%= link_to 'Toppings Manager', toppings_path, class: 'btn btn-primary' %>
  </div>

  <% if @pizzas.any? { |pizza| pizza.out_of_stock_toppings.count > 0 } %>
    <div class="alert alert-warning" role="alert">
      The toppings in red are currently out of stock.
    </div>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th style="width: 30%;">Name</th>
        <th style="width: 40%;">Toppings</th>
        <th style="width: 30%;">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @pizzas.each do |pizza| %>
        <tr>
          <td><%= pizza.name.capitalize %></td>
          <td>
            <% pizza.in_stock_toppings.each do |topping| %>
              <%= topping.name.capitalize %>
            <% end %>

            <% unless pizza.out_of_stock_toppings.empty? %>
              <br>
              <span style="color: red;">Out of stock: <%= pizza.out_of_stock_toppings.map(&:name).join(', ') %></span>
            <% end %>
          </td>
          <td>
            <div class="btn-group" role="group" aria-label="Actions">
              <%= link_to 'Edit', edit_pizza_path(pizza), class: 'btn btn-primary' %>
              <span class="mx-1"></span>
              <%= button_to 'Delete', pizza, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= button_to 'Create a new pizza', new_pizza_path, method: :get, class: 'btn btn-success' %>
</div>

app/views/pizzas/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Create a New Pizza</h1>

  <div class="mb-3">
    <%= link_to 'Menu', '/', class: 'btn btn-secondary' %>
    <%= link_to 'Toppings Manager', toppings_path, class: 'btn btn-primary' %>
  </div>

  <%= form_with(model: @pizza, local: true) do |form| %>

    <% if @pizza.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h4><%= pluralize(@pizza.errors.count, 'error') %> prohibited this pizza from being saved:</h4>
        <ul>
          <% @pizza.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, 'Pizza Name' %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :topping_ids, 'Toppings' %>
      <% @toppings.sorted_by_stock_and_name.each do |topping| %>
        <div class="form-check" id="topping_id_<%= topping.id %>">
          <%= form.check_box :topping_ids, { multiple: true, checked: false }, topping.id, nil %>
          <% if topping.in_stock %>
            <%= form.label topping.name, class: "form-check-label" %>
          <% else %>
            <%= form.label "#{topping.name} (out of stock)", class: "form-check-label", style: "color: red;" %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.submit "Create Pizza", class: "btn btn-success" %>
    </div>

  <% end %>
</div>

app/views/pizzas/show.html.erb
<div class="container mt-5">
  <h1 class="display-4"><%= @pizza.name %></h1>

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <h2 class="mt-4">Toppings</h2>
  <ul class="list-group mt-3">
    <% @pizza.toppings.each do |topping| %>
      <li class="list-group-item <%= 'text-danger' if !topping.in_stock %>"><%= topping.name %></li>
    <% end %>
  </ul>

  <div class="mt-5">
    <%= link_to 'Menu', '/', class: 'btn btn-secondary' %>
    <%= link_to 'Pizza Manager', pizzas_path, class: 'btn btn-primary' %>
    <%= link_to 'Topping Manager', toppings_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/toppings/_form.html.erb
<%= form_with(model: topping, local: true) do |form| %>
  <% if topping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topping.errors.count, "error") %> prohibited this topping from being saved:</h2>

      <ul>
        <% topping.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions" style="padding-top: 10px;">
    <%= form.submit "Create Topping", class: "btn btn-success px-4 py-2" %>
  </div>
<% end %>

app/views/toppings/edit.html.erb
<div class="container mt-5">
  <% if flash[:notice] %>
    <div class="alert alert-danger">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <h1 class="mb-4">Edit Topping</h1>

  <div class="mb-3">
    <%= link_to 'Menu', '/', class: 'btn btn-secondary' %>
    <%= link_to 'Pizza Manager', toppings_path, class: 'btn btn-primary' %>
    <%= link_to 'Toppings Manager', toppings_path, class: 'btn btn-primary' %>
  </div>

  <%= form_with(model: @topping, local: true) do |form| %>

    <div class="form-group">
      <%= form.label :name, 'Topping Name' %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.check_box :in_stock, class: "form-check-input" %>
      <%= form.label :in_stock, 'In Stock', class: "form-check-label" %>
    </div>

    <div class="form-group">
      <%= form.submit "Update Topping", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/toppings/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Toppings Manager</h1>

  <div class="mb-3">
    <%= link_to 'Menu', '/', class: 'btn btn-secondary' %>
    <%= link_to 'Pizza Manager', pizzas_path, class: 'btn btn-primary' %>
    </div>
    
  <div>
    <a href="<%= new_topping_path %>" class="btn btn-success">Create a new topping</a>
  </div>
  
  <div class="in-stock">
    <h2 class="mt-5">In Stock Toppings</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @toppings.each do |topping| %>
          <% if topping.in_stock %>
            <tr id="topping_<%= topping.id %>">
              <td><%= topping.name.capitalize %></td>
              <td><%= button_to 'Edit', edit_topping_path(topping), method: :get, class: "btn btn-primary" %></td>
              <td><%= button_to 'Mark as Out of Stock', topping_path(topping, topping: { in_stock: false }), method: :patch, class: "btn btn-warning" %></td>
              <td><%= button_to 'Delete', topping_path(topping), method: :delete, data: { confirm: 'Are you sure you want to delete this topping? This will also remove the topping from all pizzas it belongs to.' }, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div

 
  <div class="out-of-stock">
    <h2 class="mt-5">Out of Stock Toppings</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @toppings.each do |topping| %>
          <% unless topping.in_stock %>
            <tr id="topping_<%= topping.id %>">
              <td><%= topping.name.capitalize %></td>
              <td><%= button_to 'Edit', edit_topping_path(topping), method: :get, class: "btn btn-primary" %></td>
              <td><%= button_to 'Mark as In Stock', topping_path(topping, topping: { in_stock: true }), method: :patch, class: "btn btn-success" %></td>
              <td><%= button_to 'Delete', topping_path(topping), method: :delete, data: { confirm: 'Are you sure you want to delete this topping? This will also remove the topping from all pizzas it belongs to.' }, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    </div>
  <br>
</div>

app/views/toppings/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">New Topping</h1>

  <div class="mb-3">
    <%= link_to 'Menu', '/', class: 'btn btn-secondary' %>
    <%= link_to 'Pizza Manager', pizzas_path, class: 'btn btn-primary' %>
    <%= link_to 'Toppings Manager', toppings_path, class: 'btn btn-primary' %>
  </div>


  <div class="card">
    <div class="card-body">
      <%= render 'form', topping: @topping %>
    </div>
  </div>

  <%= link_to 'Back', toppings_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/toppings/show.html.erb
<div class="container mt-5">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="card">
    <div class="card-header">
      Topping Details
    </div>
    <div class="card-body">
      <p>
        <strong>Name:</strong>
        <%= @topping.name %>
      </p>

      <div class="text-center">
        <div class="mb-3">
          <%= link_to 'Menu', '/', class: 'btn btn-secondary' %>
          <%= link_to 'Pizza Manager', pizzas_path, class: 'btn btn-primary' %>
          <%= link_to 'Toppings Manager', toppings_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>